services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
  
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABAS_URL=postgres://postgres:password@db:5432/postgres
    volumes:
      - .:/app
      
volumes:
  db_data:
